# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.9.0'
  displayName: 'Install Node.js'

- script: |
    npm install request
    npm install express
    npm install body-parser
    npm install pg
    npm install
  displayName: 'npm install and build'
